📖  Update quick-start.md to include installation steps using clusterctl
kubernetes-sigs/cluster-api-addon-provider-helm pull request #93
Opened 2023-06-30 00:50 UTC by Jont828

**What this PR does / why we need it**: Update installation steps in quick start to use `clusterctl init --addon helm`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2023-07-07 22:20 UTC, Jont828 commented
/retest

2023-07-10 20:55 UTC, Jont828 commented
@dtzar I've updated the docs based on what we talked about, PTAL when you get the chance

2023-07-12 16:56 UTC, dtzar requested changes
Can you also please provide more surrounding YAML context let's say for a sample AKS cluster with this chunk?
```yaml
nginxIngressChart: enabled
```

2023-07-12 16:56 UTC, dtzar commented on docs/quick-start.md
> -### 4. Install CAAPH to the management cluster
Jumps from 3 to 5 now in overall flow.  Need to renumber below steps.

2023-07-14 01:34 UTC, Jont828 commented
@dtzar Done, how does this look?

2023-07-14 21:48 UTC, dtzar approved these changes

2023-07-14 21:48 UTC, dtzar commented
/lgtm

2023-07-14 21:50 UTC, merged